---
title: "Tree Biomass"
author: "Anthony Gardella"
date: "Wednesday, February 25, 2015"
output: html_document
---

### Data Processing 

```{r}
dat=read.csv("2011-13 Tree Biomass.csv", header=TRUE)
colnames(dat)<-c("ID","species","Plot","subplot","height","d10","init.stem.weight","bag","tot.stem.mass","leaf.mass","year","tot.mass","tot.branch.mass")

#2011 data
dat.11<-dat[dat$year==2011,]
##2011 height subset
h.11<-as.numeric(dat.11$height)
##2011 mass subset
mass.11<-as.numeric(dat.11$tot.mass)
##2011 Treatment Subset
wt.11<-dat.11[dat.11$Plot %in% c(9,10,11,12,17,18,19,20,25,26,27,28),]
dr.11<-dat.11[dat.11$Plot %in% c(1,2,3,4,21,22,23,24,33,34,35,36),]
ab.11<-dat.11[dat.11$Plot %in% c(5,6,7,8,13,14,15,16,29,30,31,32),]
w.11.h=as.numeric(wt.11$height)
w.11.tm=as.numeric(wt.11$tot.mass)
d.11.h=as.numeric(dr.11$height)
d.11.tm=as.numeric(dr.11$tot.mass)
a.11.h=as.numeric(ab.11$height)
a.11.tm=as.numeric(ab.11$tot.mass)
##2011 Plot subset
p1.11=dat.11[dat.11$Plot %in% 1,]
p2.11=dat.11[dat.11$Plot %in% 2,]
p3.11=dat.11[dat.11$Plot %in% 3,]
p4.11=dat.11[dat.11$Plot %in% 4,]
p5.11=dat.11[dat.11$Plot %in% 5,]
p6.11=dat.11[dat.11$Plot %in% 6,]
p7.11=dat.11[dat.11$Plot %in% 7,]
p8.11=dat.11[dat.11$Plot %in% 8,]
p9.11=dat.11[dat.11$Plot %in% 9,]
p10.11=dat.11[dat.11$Plot %in% 10,]
p11.11=dat.11[dat.11$Plot %in% 11,]
p12.11=dat.11[dat.11$Plot %in% 12,]
p13.11=dat.11[dat.11$Plot %in% 13,]
p14.11=dat.11[dat.11$Plot %in% 14,]
p15.11=dat.11[dat.11$Plot %in% 15,]
p16.11=dat.11[dat.11$Plot %in% 16,]
p17.11=dat.11[dat.11$Plot %in% 17,]
p18.11=dat.11[dat.11$Plot %in% 18,]
p19.11=dat.11[dat.11$Plot %in% 19,]
p20.11=dat.11[dat.11$Plot %in% 20,]
p21.11=dat.11[dat.11$Plot %in% 21,]
p22.11=dat.11[dat.11$Plot %in% 22,]
p23.11=dat.11[dat.11$Plot %in% 23,]
p24.11=dat.11[dat.11$Plot %in% 24,]
p25.11=dat.11[dat.11$Plot %in% 25,]
p26.11=dat.11[dat.11$Plot %in% 26,]
p27.11=dat.11[dat.11$Plot %in% 27,]
p28.11=dat.11[dat.11$Plot %in% 28,]
p29.11=dat.11[dat.11$Plot %in% 29,]
p30.11=dat.11[dat.11$Plot %in% 30,]
p31.11=dat.11[dat.11$Plot %in% 31,]
p32.11=dat.11[dat.11$Plot %in% 32,]
p33.11=dat.11[dat.11$Plot %in% 33,]
p34.11=dat.11[dat.11$Plot %in% 34,]
p35.11=dat.11[dat.11$Plot %in% 35,]



#2013 data
dat.13<-dat[dat$year==2013,]
##2011 height subset
h.13<-as.numeric(dat.13$height)
##2011 mass subset
mass.13<-as.numeric(dat.13$tot.mass)
#Treatment subset
wt.13<-dat.13[dat.13$Plot %in% c(9,10,11,12,17,18,19,20,25,26,27,28), ]
dr.13<-dat.13[dat.13$Plot %in% c(1,2,3,4,21,22,23,24,33,34,35,36),]
ab.13<-dat.13[dat.13$Plot %in% c(5,6,7,8,13,14,15,16,29,30,31,32),]
w.13.h=as.numeric(wt.13$height)
w.13.tm=as.numeric(wt.13$tot.mass)
d.13.h=as.numeric(dr.13$height)
d.13.tm=as.numeric(dr.13$tot.mass)
a.13.h=as.numeric(ab.13$height)
a.13.tm=as.numeric(ab.13$tot.mass)
p1.13=dat.13[dat.13$Plot %in% 1,]
p2.13=dat.13[dat.13$Plot %in% 2,]
p3.13=dat.13[dat.13$Plot %in% 3,]
p4.13=dat.13[dat.13$Plot %in% 4,]
p5.13=dat.13[dat.13$Plot %in% 5,]
p6.13=dat.13[dat.13$Plot %in% 6,]
p7.13=dat.13[dat.13$Plot %in% 7,]
p8.13=dat.13[dat.13$Plot %in% 8,]
p9.13=dat.13[dat.13$Plot %in% 9,]
p10.13=dat.13[dat.13$Plot %in% 10,]
p11.13=dat.13[dat.13$Plot %in% 11,]
p12.13=dat.13[dat.13$Plot %in% 12,]
p13.13=dat.13[dat.13$Plot %in% 13,]
p14.13=dat.13[dat.13$Plot %in% 14,]
p15.13=dat.13[dat.13$Plot %in% 15,]
p16.13=dat.13[dat.13$Plot %in% 16,]
p17.13=dat.13[dat.13$Plot %in% 17,]
p18.13=dat.13[dat.13$Plot %in% 18,]
p19.13=dat.13[dat.13$Plot %in% 19,]
p20.13=dat.13[dat.13$Plot %in% 20,]
p21.13=dat.13[dat.13$Plot %in% 21,]
p22.13=dat.13[dat.13$Plot %in% 22,]
p23.13=dat.13[dat.13$Plot %in% 23,]
p24.13=dat.13[dat.13$Plot %in% 24,]
p25.13=dat.13[dat.13$Plot %in% 25,]
p26.13=dat.13[dat.13$Plot %in% 26,]
p27.13=dat.13[dat.13$Plot %in% 27,]
p28.13=dat.13[dat.13$Plot %in% 28,]
p29.13=dat.13[dat.13$Plot %in% 29,]
p30.13=dat.13[dat.13$Plot %in% 30,]
p31.13=dat.13[dat.13$Plot %in% 31,]
p32.13=dat.13[dat.13$Plot %in% 32,]
p33.13=dat.13[dat.13$Plot %in% 33,]
p34.13=dat.13[dat.13$Plot %in% 34,]
```

```{r}




```
